version: "3"
services:
   api:
     image: dalongrong/openresty-graphql
     build: ./
     ports:
     - "8180:80"
     - "8120:8080"
     volumes:
     - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
     - "./app/:/opt/app/"
