version: "3"
services:
   api:
     image: openresty/openresty:alpine
     ports:
     - "8080:80"
     volumes:
     - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
     - "./app/:/opt/app/"
